//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kontrolnaaya2Valiev.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DevelopmentProcess
    {
        public int id { get; set; }
        public int idEmployees { get; set; }
        public int idDevelopment { get; set; }
        public string Task { get; set; }
    
        public virtual Development Development { get; set; }
        public virtual Employees Employees { get; set; }
    }
}
