//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kontrolnaaya2Valiev.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KR2_ValievEntities : DbContext
    {
        public KR2_ValievEntities()
            : base("name=KR2_ValievEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dealer> Dealer { get; set; }
        public virtual DbSet<Departament> Departament { get; set; }
        public virtual DbSet<Development> Development { get; set; }
        public virtual DbSet<DevelopmentProcess> DevelopmentProcess { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<Orderplatform> Orderplatform { get; set; }
        public virtual DbSet<Plantform> Plantform { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
