//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kontrolnaaya2Valiev.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orderplatform
    {
        public int id { get; set; }
        public int idOrder { get; set; }
        public int idPlatform { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Plantform Plantform { get; set; }
    }
}
